name = "Russia Buriat"
version = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Russia Buriat spellchecker"
bxr = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Russia Buriat, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
bxr = "TRANSLATE: A spellchecker for Russia Buriat, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.bxr"

[windows]
system_product_code = "{19BBBEEE-1756-406C-8649-B062A930F0ED}_is1"
legacy_product_codes = [
    { value = "DB2B3C08-FB2F-4982-ABB3-4079C50DD605", kind = "nsis" },
    { value = "59ACDF4B-328D-4AFA-A35D-1DD03F4D1F7D", kind = "nsis" }
]
