template = "https://github.com/giellalt/template-lang-und"
rev_id = 291
template_sha = "4f5759693f3a379d63c31d91878cd6e3b56817ae"

[replacements]
__GLOTTOLOG_ID__ = "russ1264"
__REPO__ = "lang-bxr"
__UND2C__ = "bxr"
__UNDEFINED__ = "Russia Buriat"
__UND__ = "bxr"
