template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "c0f15a905d69cb451762275644bf5c3133bfc106"

[replacements]
__GLOTTOLOG_ID__ = "russ1264"
__REPO__ = "lang-bxr"
__UND2C__ = "bxr"
__UNDEFINED__ = "Russia Buriat"
__UND__ = "bxr"
